id: P009510
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:33:48.934372
source_metadata:
  id: bdr:W1KG22266
  title: འདུལ་བའི་མདོ།
  author: ''
  volumes:
    81f290c4606942a1bc376662b176425c:
      image_group_id: I1KG22285
      title: ''
      volume_number: 1
      total_pages: 228
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
