id: IABCF83F9
legacy_id: P009510
ocr_import_info:
  bdrc_scan_id: W1KG22266
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T13:30:45'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T13:07:00.054578+00:00'
last_modified: 2022-08-31 21:07:11.697884
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22266
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22266
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་བའི་མདོ།
  author: སློབ་དཔོན་ཛི་ན་མི་ཏྲ།
statistics:
  ocr_word_mean_confidence_index: 0.7196050508006416
  ocr_word_median_confidence_index: 0.7699999809265137
quality: null
bases:
  I1KG22285:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22285
      total_pages: 228
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22285.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7196050508006416
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
